// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAgwGQhZd5-kw2JredIf5U_XA58qeaRU8',
    appId: '1:11725121453:web:3625adfdcc63f742ba6324',
    messagingSenderId: '11725121453',
    projectId: 'biodataku-15b10',
    authDomain: 'biodataku-15b10.firebaseapp.com',
    storageBucket: 'biodataku-15b10.firebasestorage.app',
    measurementId: 'G-HNLQQ8Y2YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOQIVylL3Fm1V0_CR-GGVw0NYd_okAHFk',
    appId: '1:11725121453:android:3e019c1a26275264ba6324',
    messagingSenderId: '11725121453',
    projectId: 'biodataku-15b10',
    storageBucket: 'biodataku-15b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBExFl8_myZiGUKEhqjIRpgvO8YAh7abcY',
    appId: '1:11725121453:ios:4af495ba3ed7e1a8ba6324',
    messagingSenderId: '11725121453',
    projectId: 'biodataku-15b10',
    storageBucket: 'biodataku-15b10.firebasestorage.app',
    iosBundleId: 'com.fenq.biodataku.biodataku',
  );
}
